---
  - name: Create {{ db_name }} database
    mysql_db:
      name: "{{ db_name }}" 
      state: present

  # - name: ensure roundcube database user is present
  #   mysql_user:
  #     name: "{{ db_user }}"
  #     host: localhost
  #     password: "{{ db_pass }}"
  #     priv: '*.*:ALL,GRANT'
  #     state: present
  #     # with_items:
  #     #   - "%"
  #     #   - localhost

#  - name: ensure {{ db_name }} database user is present
#    #shell: mysql -e "CREATE USER '{{ db_user }}'@'%' IDENTIFIED BY '{{ db_pass }}';"
#    shell: mysql -e "grant all privileges on {{ db_name }}.* to {{ db_user }}@{{ RemoteServer }} identified by '{{ db_pass }}';"
#    notify: "mariadb restart"
    
