---
# handlers file for roles/ntp
  - name: Reload firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded
      enabled: yes
    listen: "firewall reload"

  - name: Reload Chronyd
    ansible.builtin.service:
      name: chronyd
      state: restarted
      enabled: yes
    listen: "chronyd reload"
