---
# handlers file for roles/syslog
  - name: Reload rsyslog
    ansible.builtin.service:
      name: rsyslog
      state: restarted
      enabled: yes
    listen: "rsyslog reload"

  - name: Reload firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded
      enabled: yes
    listen: "firewall reload"