---
  - name: "Updating firewall for Rsyslog tcp port"
    firewalld:
      port: 514/tcp
      permanent: yes
      state: enabled
    when: inventory_hostname in groups['syslogserver']

  - name: "Updating firewall for Rsyslog udp port"
    firewalld:
      port: 514/udp
      permanent: yes
      state: enabled
    notify: "firewall reload"
    when: inventory_hostname in groups['syslogserver']

  - name: Disable selinux
    selinux:
      state: disabled
