---
  - name: Updating firewall rules for {{ item }}
    firewalld:
      service: "{{ item }}"
      permanent: yes
      state: enabled
    loop:
      - http
      - https
    notify: "firewall restart"

  - name: Disable selinux
    selinux:
      state: disabled
